config/routes.rb
Rails.application.routes.draw do
  root action: :index, controller: :people
  resources :people
  devise_for :users
  
  get '/affidavits/:who_nickname/:where_nickname', controller: :affidavits, action: :show_or_create, as: :show_or_create_affidavits
  resources :affidavits, only: %i(show create destroy)
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id                       :bigint           not null, primary key
#  city                     :string
#  first_name               :string
#  house_number             :string
#  id_number                :string
#  last_name                :string
#  nickname                 :string
#  phone_number             :string
#  preferred_affidavit_type :string
#  preferred_note           :string
#  preferred_reason         :string
#  street                   :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  user_id                  :bigint           not null
#
# Indexes
#
#  index_people_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Person < ApplicationRecord
  belongs_to :user
  has_one_attached :signature

  before_save :unaccent_nickname

  validates *%i(
    first_name
    last_name
    nickname
  ), presence: true

  def unaccent_nickname
    self.nickname = I18n.transliterate(nickname).downcase
  end

  def display_name
    [first_name, last_name].join(' ')
  end

  def place
    "#{street} #{house_number}, #{city}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = model.where(user: current_user)
    @affidavits = current_user.affidavits
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = model.new(user: current_user)
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = model.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :nickname, :id_number, :phone_number, :street, :house_number, :city, :preferred_reason, :preferred_note, :preferred_affidavit_type, :user_id, :signature)
    end

    def model
      Person
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :id_number
    = f.text_field :id_number
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :house_number
    = f.text_field :house_number
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :preferred_affidavit_type
    = f.select :preferred_affidavit_type, [["Region", "region"]]
  .field
    = f.label :preferred_reason
    = f.select :preferred_reason, %i(doctor other_person state work death school event travel self_emloyment).map(& ->(reason) {[reason.to_s.humanize, reason.to_s]})
  .field
    = f.label :preferred_note
    = f.text_area :preferred_note
  .field
    = f.label :signature
    - if @person.signature.present?
      = image_tag url_for(@person.signature), width: 200
      br/
    = f.file_field :signature
  .field
    = f.hidden_field :user_id
  .actions = f.submit

app/views/people/edit.html.slim
h1 Editing person

== render 'form'

=> link_to 'Show', @person
'|
=< link_to 'Back', people_path

app/views/people/index.html.slim
= render 'shared/flash'

h1 Listing people

table
  thead
    tr
      th First name
      th Last name
      th Nickname
      th Id number
      th Phone number
      th Street
      th Houser number
      th City
      th Preferred reason
      th Preferred note
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = person.first_name
        td = person.last_name
        td = person.nickname
        td = person.id_number
        td = person.phone_number
        td = person.street
        td = person.house_number
        td = person.city
        td = person.preferred_reason
        td = person.preferred_note
        td = link_to 'Show', person
        td = link_to 'Edit', edit_person_path(person)
        td = link_to 'Destroy', person, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Person', new_person_path

h1 Listing Affidavits

table
  thead
    tr
      th Who
      th Where
      th Reason
      th Note
      th When
      th

  tbody
    - @affidavits.each do |affidavit|
      tr
        td = affidavit.who&.display_name
        td = affidavit.where&.display_name
        td = affidavit.reason&.humanize
        td = affidavit.note
        td = affidavit.rounded_time
        td = link_to 'Show', affidavit
        td = link_to 'PDF', affidavit_url(id: affidavit.id, format: :pdf)
        td = link_to 'Destroy', affidavit, method: :delete

| You can also access affidavits directly on 
= root_url + 'affidavits/:who_nickname/:where_nickname.pdf'

h1 Create new Affidavit

= form_for current_user.affidavits.build do |f|
  .field
    = f.label :who
    = f.select :who, @people.map(& -> (person) { [person&.display_name, person.id]})
  .field
    = f.label :where
    = f.select :where, @people.map(& -> (person) { [person&.display_name, person.id]}), selected: @people.second&.id
  .field
    = f.label :affidavit_type
    = f.select :affidavit_type, [['Region', 'region']]
  .field
    = f.label :reason
    = f.select :reason, %i(doctor other_person state work death school event travel self_emloyment).map(& ->(reason) {[reason.to_s.humanize, reason.to_s]}), selected: :other_person
  .field
    = f.label :note
    = f.text_area :note
  .actions = f.submit

app/views/people/new.html.slim
h1 New person

== render 'form'

= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice = notice

p
  strong First name:
  = @person.first_name
p
  strong Last name:
  = @person.last_name
p
  strong Nickname:
  = @person.nickname
p
  strong Id number:
  = @person.id_number
p
  strong Phone number:
  = @person.phone_number
p
  strong Street:
  = @person.street
p
  strong Houser number:
  = @person.house_number
p
  strong City:
  = @person.city
p
  strong Preferred reason:
  = @person.preferred_reason
p
  strong Preferred note:
  = @person.preferred_note

=> link_to 'Edit', edit_person_path(@person)
'|
=< link_to 'Back', people_path